keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
keySdlStep
send2pid -1 1 sRegistrarUsuario |{param1|=0|}
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
sdlTransition
stepout
